/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { BatchSettingsOptions } from './batchSettingsOptions';

export interface BatchSettings {
  ids: string[];
  command: string;
  options?: BatchSettingsOptions;
}
