/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */

export interface ConfiguratorAdvancedSettings {
  installation_pack?: string;
  bitcart_docker_repository?: string;
  additional_components?: string[];
}
