/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { ConfiguratorAdvancedSettings } from './configuratorAdvancedSettings';
import type { ConfiguratorDeploySettingsCoins } from './configuratorDeploySettingsCoins';
import type { ConfiguratorDomainSettings } from './configuratorDomainSettings';
import type { ConfiguratorSSHSettings } from './configuratorSSHSettings';

export interface ConfiguratorDeploySettings {
  domain_settings?: ConfiguratorDomainSettings;
  coins?: ConfiguratorDeploySettingsCoins;
  additional_services?: string[];
  advanced_settings?: ConfiguratorAdvancedSettings;
  mode: string;
  ssh_settings?: ConfiguratorSSHSettings;
}
