/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { CreateNotificationData } from './createNotificationData';
import type { CreateNotificationMetadata } from './createNotificationMetadata';

export interface CreateNotification {
  metadata?: CreateNotificationMetadata;
  created?: string;
  name: string;
  provider: string;
  data: CreateNotificationData;
}
