/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { CreateTemplateMetadata } from './createTemplateMetadata';

export interface CreateTemplate {
  metadata?: CreateTemplateMetadata;
  created?: string;
  name: string;
  text: string;
}
