/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { CreatePayoutMetadata } from './createPayoutMetadata';

export interface CreatePayout {
  metadata?: CreatePayoutMetadata;
  created?: string;
  amount: number;
  destination: string;
  store_id: string;
  wallet_id: string;
  currency?: string;
  notification_url?: string;
  max_fee?: number;
  status?: string;
}
