/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { CreateWalletAdditionalXpubData } from './createWalletAdditionalXpubData';
import type { CreateWalletMetadata } from './createWalletMetadata';

export interface CreateWallet {
  metadata?: CreateWalletMetadata;
  created?: string;
  name: string;
  xpub?: string;
  currency?: string;
  lightning_enabled?: boolean;
  label?: string;
  hint?: string;
  contract?: string;
  additional_xpub_data?: CreateWalletAdditionalXpubData;
}
