/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { CreateDiscountMetadata } from './createDiscountMetadata';

export interface CreateDiscount {
  metadata?: CreateDiscountMetadata;
  created?: string;
  name: string;
  percent: number;
  end_date: string;
  description?: string;
  promocode?: string;
  currencies?: string;
}
