/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { DisplayUserMetadata } from './displayUserMetadata';
import type { UserPreferences } from './userPreferences';

export interface DisplayUser {
  metadata?: DisplayUserMetadata;
  created?: string;
  email: string;
  is_superuser?: boolean;
  settings?: UserPreferences;
  id?: string;
  is_verified: boolean;
  is_enabled: boolean;
  totp_key: string;
  totp_url: string;
  tfa_enabled: boolean;
  fido2_devices: unknown[];
}
