/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */

export type ExportInvoicesInvoicesExportGetParams = {
  export_format?: string;
  add_payments?: boolean;
  all_users?: boolean;
  offset?: number;
  limit?: number;
  query?: string;
  multiple?: boolean;
  sort?: string;
  desc?: boolean;
};
