/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { FileMetadata } from './fileMetadata';

export interface File {
  metadata?: FileMetadata;
  created?: string;
  id: string;
  filename: string;
  user_id: string;
}
