/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */

export type GetNumberOfProductsProductsCountGetParams = {
  store?: string;
  category?: string;
  min_price?: number;
  max_price?: number;
  sale?: boolean;
  offset?: number;
  limit?: number;
  query?: string;
  multiple?: boolean;
  sort?: string;
  desc?: boolean;
};
