/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { HTTPCreateLoginTokenMetadata } from './hTTPCreateLoginTokenMetadata';

export interface HTTPCreateLoginToken {
  metadata?: HTTPCreateLoginTokenMetadata;
  created?: string;
  app_id?: string;
  redirect_url?: string;
  permissions?: string[];
  email?: string;
  password?: string;
  captcha_code?: string;
  strict?: boolean;
}
