/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { OptionalStoreCurrencyData } from './optionalStoreCurrencyData';
import type { OptionalStoreMetadata } from './optionalStoreMetadata';
import type { OptionalStoreTemplates } from './optionalStoreTemplates';
import type { StoreCheckoutSettings } from './storeCheckoutSettings';
import type { StorePluginSettings } from './storePluginSettings';
import type { StoreThemeSettings } from './storeThemeSettings';

export interface OptionalStore {
  metadata?: OptionalStoreMetadata;
  created?: string;
  name?: string;
  default_currency?: string;
  email?: string;
  checkout_settings?: StoreCheckoutSettings;
  theme_settings?: StoreThemeSettings;
  email_host?: string;
  email_port?: number;
  email_user?: string;
  email_password?: string;
  email_use_ssl?: boolean;
  wallets?: string[];
  notifications?: string[];
  templates?: OptionalStoreTemplates;
  plugin_settings?: StorePluginSettings;
  id?: string;
  user_id?: string;
  currency_data?: OptionalStoreCurrencyData;
}
