/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { OptionalPayoutMetadata } from './optionalPayoutMetadata';

export interface OptionalPayout {
  metadata?: OptionalPayoutMetadata;
  created?: string;
  amount?: string;
  destination?: string;
  store_id?: string;
  wallet_id?: string;
  currency?: string;
  notification_url?: string;
  max_fee?: number;
  status?: string;
  id?: string;
  user_id?: string;
  tx_hash?: string;
  used_fee?: number;
}
