/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { OptionalCreateWalletAdditionalXpubData } from './optionalCreateWalletAdditionalXpubData';
import type { OptionalCreateWalletMetadata } from './optionalCreateWalletMetadata';

export interface OptionalCreateWallet {
  metadata?: OptionalCreateWalletMetadata;
  created?: string;
  name?: string;
  xpub?: string;
  currency?: string;
  lightning_enabled?: boolean;
  label?: string;
  hint?: string;
  contract?: string;
  additional_xpub_data?: OptionalCreateWalletAdditionalXpubData;
}
