/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { OptionalNotificationData } from './optionalNotificationData';
import type { OptionalNotificationMetadata } from './optionalNotificationMetadata';

export interface OptionalNotification {
  metadata?: OptionalNotificationMetadata;
  created?: string;
  name?: string;
  provider?: string;
  data?: OptionalNotificationData;
  id?: string;
  user_id?: string;
}
