/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { Notification } from './notification';

export interface PaginationResponseNotification {
  count: number;
  next?: string;
  previous?: string;
  result: Notification[];
}
