/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { Template } from './template';

export interface PaginationResponseTemplate {
  count: number;
  next?: string;
  previous?: string;
  result: Template[];
}
