/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { Store } from './store';

export interface PaginationResponseStore {
  count: number;
  next?: string;
  previous?: string;
  result: Store[];
}
