/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { PolicyEmailSettings } from './policyEmailSettings';
import type { PolicyExplorerUrls } from './policyExplorerUrls';
import type { PolicyRpcUrls } from './policyRpcUrls';

export interface Policy {
  disable_registration?: boolean;
  require_verified_email?: boolean;
  allow_file_uploads?: boolean;
  discourage_index?: boolean;
  check_updates?: boolean;
  staging_updates?: boolean;
  allow_anonymous_configurator?: boolean;
  captcha_sitekey?: string;
  captcha_secretkey?: string;
  admin_theme_url?: string;
  enable_captcha?: boolean;
  explorer_urls?: PolicyExplorerUrls;
  rpc_urls?: PolicyRpcUrls;
  email_settings?: PolicyEmailSettings;
}
