/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { ProductMetadata } from './productMetadata';
import type { ProductTemplates } from './productTemplates';

export interface Product {
  metadata?: ProductMetadata;
  created?: string;
  status?: string;
  price: string;
  quantity: number;
  name: string;
  download_url?: string;
  description?: string;
  category?: string;
  image?: string;
  store_id?: string;
  discounts?: string[];
  templates?: ProductTemplates;
  id?: string;
  user_id: string;
}
