/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */

export interface SSHSettings {
  host?: string;
  port?: number;
  username?: string;
  password?: string;
  key_file?: string;
  key_file_password?: string;
  authorized_keys_file?: string;
  bash_profile_script?: string;
}
