/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */

export interface StoreCheckoutSettings {
  expiration?: number;
  transaction_speed?: number;
  underpaid_percentage?: number;
  custom_logo_link?: string;
  recommended_fee_target_blocks?: number;
  show_recommended_fee?: boolean;
  use_dark_mode?: boolean;
  use_html_templates?: boolean;
  email_required?: boolean;
  ask_address?: boolean;
  randomize_wallet_selection?: boolean;
  allow_anonymous_invoice_creation?: boolean;
  include_network_fee?: boolean;
  rate_rules?: string;
  pos_screen_enabled?: boolean;
}
