/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { StoreCheckoutSettings } from './storeCheckoutSettings';
import type { StoreCurrencyData } from './storeCurrencyData';
import type { StoreMetadata } from './storeMetadata';
import type { StorePluginSettings } from './storePluginSettings';
import type { StoreTemplates } from './storeTemplates';
import type { StoreThemeSettings } from './storeThemeSettings';

export interface Store {
  metadata?: StoreMetadata;
  created?: string;
  name: string;
  default_currency?: string;
  email?: string;
  checkout_settings?: StoreCheckoutSettings;
  theme_settings?: StoreThemeSettings;
  email_host?: string;
  email_port?: number;
  email_user?: string;
  email_password?: string;
  email_use_ssl?: boolean;
  wallets: string[];
  notifications?: string[];
  templates?: StoreTemplates;
  plugin_settings?: StorePluginSettings;
  id?: string;
  user_id: string;
  currency_data: StoreCurrencyData;
}
