/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { TemplateMetadata } from './templateMetadata';

export interface Template {
  metadata?: TemplateMetadata;
  created?: string;
  name: string;
  text: string;
  id?: string;
  user_id: string;
}
