/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * BitcartCC
 * BitcartCC Merchants API
 * OpenAPI spec version: 0.7.4.1
 */
import type { WalletAdditionalXpubData } from './walletAdditionalXpubData';
import type { WalletMetadata } from './walletMetadata';

export interface Wallet {
  metadata?: WalletMetadata;
  created?: string;
  name: string;
  xpub?: string;
  currency?: string;
  lightning_enabled?: boolean;
  label?: string;
  hint?: string;
  contract?: string;
  additional_xpub_data?: WalletAdditionalXpubData;
  id?: string;
  user_id: string;
  error?: boolean;
  balance: string;
  xpub_name: string;
}
