# Our Node base image
FROM node:20.2.0-bullseye

# Set the Node environment to development to ensure all packages are installed
ENV NODE_ENV development

# Change our current working directory
WORKDIR /usr/src/app

# Copy over `package.json` and lock files to optimize the build process
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "yarn.lock", "./"]

# Copy over rest of the project files
COPY . .

# Install Node modules
RUN yarn

# Dist directory
RUN yarn package

# build
RUN yarn build


# Expose port 3000 for the SvelteKit app and 24678 for Vite's HMR
EXPOSE 3000

# Run `yarn start`
CMD ["yarn", "start"]