export enum PermissionType {
  IMPERSONATE_CREATOR = 'IMPERSONATE CREATOR',
  IMPERSONATE_AGENT = 'IMPERSONATE AGENT',
  CREATE_CREATOR = 'CREATE CREATOR',
  FULL = 'FULL',
  NONE = 'NONE',
  CREATE_AGENT = 'CREATE AGENT',
  CREATE_OPERATOR = 'CREATE OPERATOR',
  CREATE_TICKET = 'CREATE TICKET',
  CREATE_SHOW = 'CREATE SHOW',
  UPDATE_PROFILE = 'UPDATE PROFILE',
  CANCEL_SHOW = 'CANCEL SHOW',
  CREATE_PAYOUT = 'CREATE PAYOUT'
}
