import type { LinkMachineServiceType, LinkMachineStateType } from '$lib/machines/linkMachine';
import type { TalentDBType } from '$lib/ORM/dbs/talentDB';
import type { LinkDocument } from '$lib/ORM/models/link';
import type { TalentDocument } from '$lib/ORM/models/talent';
import { writable } from 'svelte/store';
export const talent = writable<TalentDocument | null>(null);
export const talentDB = writable<TalentDBType | null>(null);
export const currentLink = writable<LinkDocument | null>(null);
export const linkMachineState = writable<LinkMachineStateType | null>(null);
export const linkMachineService = writable<LinkMachineServiceType | null>(null);